### ISSUE TITLE
Example factory hooks.

### ISSUE THREAD

**Issue by damontgomery** [acquia/bolt#21]
Including caching settings, etc.

**Comment by grasmash** [comment]
More specifically, create example hooks in pre-settings-php and post-settings-php that require cache.settings.php, and other things that are done in docroot/sites/default/settings.php.

**Comment by kylebrowning** [comment]
@grasmash Where exactly do you want this examples to go?

**Comment by grasmash** [comment]
I would think they'd be nice to put in the factory-hooks dir. Would that be wiped out by the acsf initialization?

**Comment by kylebrowning** [comment]
No its not wiped, just wondering if anything needs to happen to make sure bolt carries the directories over.

**Comment by grasmash** [comment]
If you just create template/factory-hooks, it should ship with new projects.
